# Set up verbose commands
/control/verbose 0
/run/verbose 0
/run/initialize
/tracking/verbose 0
/event/verbose 0

/gps/ene/mono 122 keV
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 3 mm
/gps/position 0 0 19.0 mm
/gps/ang/type iso
/gps/ang/maxtheta 20 deg
/analysis/setFileName /home/apiers/selena/aSe0vBB/particle/pixel_200umaSe_disksource_500nm_122kev_100k.root
/run/setCut 0.5 um
/run/beamOn 100000


